config/routes.rb
PolicyManager::Engine.routes.draw do

  get "documentation", to: "application#doc", as: :documentation

  resources :user_portability_requests, only: [:index, :create, :destroy]

  resources :portability_requests, only: [:index, :destroy] do
    member do
      get :confirm
    end
  end
  
  resources :categories, only: [:show, :index] do 
    resources :terms, except: [:index]
  end

  resources :user_terms, only: [:show] do 
    collection do 
      get :pending
      put :accept_multiples
      get :blocking_terms
    end
    
    member do
      put :accept 
      put :reject 
    end
  end
  
  root 'categories#index'
end

app/models/policy_manager/application_record.rb
module PolicyManager
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/policy_manager/portability_request.rb
require "paperclip"
require "aasm"

module PolicyManager
  class PortabilityRequest < ApplicationRecord
    include Paperclip::Glue

    belongs_to :user, class_name: Config.user_resource.to_s, foreign_key:  :user_id

    has_attached_file :attachment,
      path: Config.exporter.try(:attachment_path) || Rails.root.join("tmp/portability/:id/build.zip").to_s,
      storage: Config.exporter.try(:attachment_storage) || :filesystem,
      s3_permissions: :private

    do_not_validate_attachment_file_type :attachment

    include AASM

    aasm column: :state do
      state :pending, :initial => true, :after_enter => :notify_progress_to_admin
      state :progress, :after_enter => :handle_progress
      state :completed, :after_enter => :notify_completeness

      event :confirm do
        transitions from: :pending, to: :progress
      end

      event :complete do
        transitions from: :progress, to: :completed
      end
    end

    def user_email
      self.user.email
    end

    def file_remote_url=(url_value)
      self.attachment = File.open(url_value) unless url_value.blank?
      self.save
      self.complete!
    end

    def download_link
      url = self.attachment.expiring_url(PolicyManager::Config.exporter.expiration_link)
      PolicyManager::Config.exporter.customize_link(url)
    end

    def handle_progress
      notify_progress
      perform_job
    end

    def perform_job
      ExporterJob.set(queue: :default).perform_later(self.user.id)
    end

    def notify_progress
      PortabilityMailer.progress_notification(self.id).deliver_now
    end

    def notify_progress_to_admin
      PortabilityMailer.admin_notification(self.user.id).deliver_now
    end

    def notify_completeness
      PortabilityMailer.completed_notification(self.id).deliver_now
    end

  end
end

app/models/policy_manager/term.rb
require "redcarpet"
require "aasm"

module PolicyManager
  class Term < ApplicationRecord
    include AASM

    validates_presence_of :rule
    validates_presence_of :description
    validates_presence_of :state

    aasm :column => :state do
      state :draft, :initial => true # db column's default
      state :published

      event :publish do
        transitions from: :draft, to: :published
      end

      event :unpublish do
        transitions from: :published, to: :draft
      end

    end

    def self.renderer
      @markdown = markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    end

    def to_html
      self.class.renderer.render(self.description)
    end

    def rule
      PolicyManager::Config.rules.find{|o| o.name == self[:rule]}
    end
  end
end

app/controllers/policy_manager/application_controller.rb
module PolicyManager
  class ApplicationController < ActionController::Base

    if defined? Doorman
      include Doorman::Controller
    end

    before_action :user_authenticated?
    before_action :set_language

    def allow_admins
      return redirect_to pending_user_terms_path unless Config.is_admin?(current_user)
    end

    def doc
      require "redcarpet"
      @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, fenced_code_blocks: true)
      lines = File.open( PolicyManager::Engine.root.join("README.md")).readlines
      @html = @markdown.render(lines.join(""))
      render "policy_manager/doc"
      #render inline: html, layout: "policy_manager/application"
    end

    def user_authenticated?
      if !current_user
        render :file => "policy_manager/401.erb", 
        :layout => "policy_manager/blank", 
        :status => :unauthorized
      end
    end

    def set_language
      I18n.locale = Config.user_language(current_user)
    end

    def current_user
      @_current_user ||=  super || (Config.has_different_admin_user_resource? && admin_user)
    end

    def admin_user
      self.send("current_#{Config.admin_user_resource.name.underscore}")
    end

    protect_from_forgery with: :exception
  end
end

app/controllers/policy_manager/categories_controller.rb
require_dependency "policy_manager/application_controller"

module PolicyManager
  class CategoriesController < ApplicationController

    before_action :allow_admins

    # GET /categories
    def index
      @categories = PolicyManager::Config.rules
    end

    # GET /categories/1
    def show
      @category = PolicyManager::Config.rules.find{|o| o.name == params[:id]}
      @terms = @category.terms.paginate(:page => params[:page], 
                                        :per_page => 12)
    end

    private
  end
end

app/controllers/policy_manager/exporter_controller.rb
module PolicyManager
  class ExporterController < ActionController::Base

    include ExporterHelper 

  end
end

app/controllers/policy_manager/portability_requests_controller.rb
require_dependency "policy_manager/application_controller"
module PolicyManager
  class PortabilityRequestsController < ApplicationController
    
    before_action :set_portability_request, only: :destroy
    before_action :allow_admins

    # GET /portability_requests
    def index
      @portability_requests = PortabilityRequest.order(created_at: :desc)
                                                .paginate(
                                                  :page => params[:page], 
                                                  :per_page => 10
                                                )
    end

    def confirm
      @portability_request = PortabilityRequest.find(params[:id])
      if @portability_request.confirm!
        redirect_to portability_requests_path
      end
    end

    # DELETE /portability_requests/1
    def destroy
      @portability_request = PortabilityRequest.find(params[:id]).destroy
      redirect_to portability_requests_url, notice: I18n.t("terms_app.portability_requests.index.destroyed")
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_portability_request
      @portability_request = PortabilityRequest.find(params[:id])
    end

  end
end

app/controllers/policy_manager/terms_controller.rb
require_dependency "policy_manager/application_controller"

module PolicyManager
  class TermsController < ApplicationController
    before_action :set_term, only: [:show, :edit, :update, :destroy]
    before_action :allow_admins
    
    # GET /terms/1
    def show
    end

    # GET /terms/new
    def new
      @term = Term.new
    end

    # GET /terms/1/edit
    def edit
    end

    # POST /terms
    def create
      @term = Term.new(term_params)

      if @term.save
        redirect_to category_term_path(@term.rule.name, @term), notice: I18n.t("terms_app.terms.new.created")
      else
        render :new
      end
    end

    # PATCH/PUT /terms/1
    def update
      if @term.update(term_params)
        redirect_to category_term_path(@term.rule.name, @term), notice: I18n.t("terms_app.terms.new.updated")
      else
        render :edit
      end
    end

    # DELETE /terms/1
    def destroy
      @term.destroy
      redirect_to category_terms_path(@term.rule.name), notice: I18n.t("terms_app.terms.new.destroyed")
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def term_params
      params.require(:term).permit(:description, :rule, :state)
    end
    
  end
end

app/controllers/policy_manager/user_portability_requests_controller.rb
require_dependency "policy_manager/application_controller"

module PolicyManager
  class UserPortabilityRequestsController < ApplicationController

    def index
      @user_portability_requests = current_user.portability_requests
                                               .order(created_at: :desc)
                                               .paginate(
                                                :page => params[:page], 
                                                :per_page => 10)
    end

    def create
      respond_to do |format|
       
          if current_user.can_request_portability?
            if current_user.portability_requests.create
              format.html{
                redirect_to user_portability_requests_path, notice: I18n.t("terms_app.user_portability_requests.index.created")
              }
              format.json{
                render json: {notice: I18n.t("terms_app.user_portability_requests.index.created")}
              }
            end
          else
            format.html{
              redirect_to user_portability_requests_path, notice: I18n.t("terms_app.user_portability_requests.index.has_pending")
            }
            format.json{
              render json: {notice: I18n.t("terms_app.user_portability_requests.index.has_pending")}, status: 422  
            }
          end
        
      end
    end

    #def destroy
    #  PortabilityRequest.find(params[:id]).destroy
    #  redirect_to user_portability_requests_url, notice: I18n.t("terms_app.portability_requests.index.destroyed")
    #end

  end
end

app/controllers/policy_manager/user_terms_controller.rb
require_dependency "policy_manager/application_controller"

module PolicyManager
  class UserTermsController < ApplicationController

    skip_before_action :user_authenticated?, only: [:show, :accept, :reject, :blocking_terms]
    before_action :set_user_term, only: [:accept, :reject, :show, :edit, :update, :destroy]

    # GET /user_terms/1
    def show
      @user_term = current_user.present? ? current_user.handle_policy_for(@term) : UserTerm.new(term: @term, user: nil, state: cookies["policy_rule_#{@term.rule.name}"])
    end

    # GET /pending
    def pending
      @pending_policies = current_user.pending_policies
      respond_to do |format|
        format.html{ }
        format.json{ render json: @pending_policies }
      end
    end

    # GET /blocking_terms
    def blocking_terms
      respond_to do |format|
        format.html{ }
        format.json{ render json: PolicyManager::Config.rules
                                                       .select{|p| p.blocking }
                                                       .map(&:name) 
        }
      end
    end

    def accept_multiples
      rules = current_user.pending_policies.map{|o| "policy_rule_#{o.name}"}
      resource_params = params.require(:user).permit(rules)
      current_user.update_attributes(resource_params)
      @pending_policies = current_user.pending_policies
      
      respond_to do |format|
        format.html{ }
        format.json{ render json: @pending_policies }
      end
    end

    def accept
      
      handle_term_accept

      respond_to do |format|
        format.html{ 
          if @user_term.errors.any?
            redirect_to root_url , notice: "hey there are some errors! #{@user_term.errors.full_messages.join()}"
          else
            redirect_to root_url 
          end
        }
        format.js
        format.json{
          render json: {
            status: @user_term ? @user_term.state : cookies["policy_rule_#{@term.rule.name}"]
          }
        }
      end
    end

    def reject
      handle_term_reject

      respond_to do |format|
        format.html{ 
          if @user_term.errors.any?
            redirect_to root_url , notice: "hey there are some errors! #{@user_term.errors.full_messages.join()}"
          else
            redirect_to root_url 
          end
        }
        format.js
        format.json{
          if @user_term.present? && @user_term.errors.any?
            render json: { url: root_url , notice: "hey there are some errors! #{@user_term.errors.full_messages.join()}" }
          else
            render json: {
              state: @user_term ? @user_term.state : cookies["policy_rule_#{@term.rule.name}"]
            }
          end
        }
      end
    end

=begin
    # GET /user_terms/new
    def new
      @user_term = UserTerm.new
    end

    # POST /user_terms
    def create
      @user_term = UserTerm.new(user_term_params)

      if @user_term.save
        redirect_to @user_term, notice: 'User term was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /user_terms/1
    def update
      if @user_term.update(user_term_params)
        redirect_to @user_term, notice: 'User term was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /user_terms/1
    def destroy
      @user_term.destroy
      redirect_to user_terms_url, notice: 'User term was successfully destroyed.'
    end
=end

    private

      def handle_term_accept
        if current_user
          @user_term = current_user.handle_policy_for(@term)
          if @user_term.accept!
            @term.rule.on_accept.call(self) if @term.rule.on_accept.is_a?(Proc)
          end
        end

        cookies["policy_rule_#{@term.rule.name}"] = {
          :value => "accepted",
          :expires => 1.year.from_now
        }
      end

      def handle_term_reject
        if current_user
          @user_term = current_user.handle_policy_for(@term)
          if @user_term.reject!
            @term.rule.on_reject.call(self) if @term.rule.on_reject.is_a?(Proc)
          end
        end

        cookies.delete("policy_rule_#{@term.rule.name}")
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_user_term
        @category = PolicyManager::Config.rules.find{|o| o.name == params[:id]}
        @term = @category.terms.last
      end

      # Only allow a trusted parameter "white list" through.
      def user_term_params
        params.fetch(:user_term, {})
      end
  end
end

app/helpers/policy_manager/application_helper.rb
module PolicyManager
  module ApplicationHelper

    def bootstrap_class_for flash_type
      { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
    end

    def flash_messages(opts = {})

      flash.each do |msg_type, message|
        flash.delete(msg_type)
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}") do 
          concat content_tag(:button, "<i class='fa fa-times-circle'></i>".html_safe, class: "close", data: { dismiss: 'alert' })
          concat message 
        end)
      end

      session.delete(:flash)
      nil
    end

    def state_color(state)
      case state
      when "pending", "draft"
        return "tag-yellow"
      when "progress"
        return "tag-azure"
      when "completed", "published"
        return "tag-green"
      end
    end

    def gravatar_url(user, size)
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    end

    def chart(data)
      begin
        column_chart(data.call)
      rescue Groupdate::Error
        content_tag(:p, "chart not displayed, Be sure to install time zone support - https://github.com/ankane/groupdate#for-mysql", class: "alert alert-danger")
      end
    end

  end
end

app/helpers/policy_manager/exporter_helper.rb
module PolicyManager
  module ExporterHelper

    def image_tag(remote_image, opts={})
      begin
        basename = File.basename(remote_image)
        id = opts[:id] || SecureRandom.hex(10)
        composed_name = [id, basename].compact.join("-")
        path = "#{File.dirname(@base_path)}/#{composed_name}"
        save_image(remote_image, path)
        tag(:img, {src: "./#{id}-#{File.basename(URI(remote_image).path)}" }.merge(opts))
      rescue => e
        Config.error_notifier_method(e)
        content_tag(:p, "broken image")
      end
    end

    private

    def save_image(remote_image, path)
      open(URI(path).path, 'wb') do |file|
        file << open(remote_image).read
      end
    end
    
  end
end

app/helpers/policy_manager/portability_requests_helper.rb
module PolicyManager
  module PortabilityRequestsHelper
  end
end

app/helpers/policy_manager/scripts_helper.rb
module PolicyManager
  module ScriptsHelper

    def render_scripts
      PolicyManager::Script.scripts.map do |c|
        render( partial: c.script) if c.can_render?
      end.compact.join(" ").html_safe
    end

  end
end

app/helpers/policy_manager/terms_helper.rb
module PolicyManager
  module TermsHelper

    def render_term_for(policy)
      return if policy.nil?
      PolicyManager::Config.rules.find{|o| o.name == policy}.terms.published.last
    end

  end
end

app/helpers/policy_manager/user_portability_requests_helper.rb
module PolicyManager
  module UserPortabilityRequestsHelper
  end
end

app/helpers/policy_manager/user_terms_helper.rb
module PolicyManager
  module UserTermsHelper
  end
end

app/views/policy_manager/shared/_footer.erb
<footer class="footer">
  <div class="container">
    <div class="row align-items-center flex-row-reverse">
      <div class="col-auto ml-lg-auto">
        <div class="row align-items-center">
          <div class="col-auto">
            <ul class="list-inline list-inline-dots mb-0">
              <li class="list-inline-item">
                <a href="<%= documentation_path %>">
                Documentation
                </a>
              </li>

            </ul>
          </div>
          <div class="col-auto">
            <a href="https://github.com/prey/gdpr_rails" class="btn btn-outline-primary btn-sm">Source code</a>
          </div>
        </div>
      </div>

      <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
        with <i class="fa fa-heart"></i> by <a href=".">Preyproject</a>. Theme by <a href="https://codecalm.net" target="_blank">codecalm.net</a>
      </div>
    </div>
  </div>
</footer>

app/views/policy_manager/shared/_header.erb
<div class="header py-4">
  <div class="container">
    <div class="d-flex">

      <a class="header-brand" href="<%= root_url %>">
        <%= I18n.t("terms_app.sub_title") %>
        <!--<img src="./demo/brand/tabler.svg" class="header-brand-img" alt="tabler logo">-->
      </a>

      <div class="d-flex order-lg-2 ml-auto">

        <div class="dropdown">
          <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
            <span class="avatar" style="background-image: url(<%= gravatar_url(controller.current_user, 40)%>)"></span>
            <span class="ml-2 d-none d-lg-block">
              <span class="text-default">
                <%= controller.current_user.email %>
              </span>
              <% if PolicyManager::Config.is_admin?(controller.current_user) %>
                <small class="text-muted d-block mt-1">Administrator</small>
              <% end %>
            </span>
          </a>

          <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
            <!--
            <a class="dropdown-item" href="#">
              <i class="dropdown-icon fe fe-user"></i> Profile
            </a>
            <div class="dropdown-divider"></div>
            -->

            <% if PolicyManager::Config.logout_url.present? %>
              <a class="dropdown-item" href="<%= PolicyManager::Config.logout_url %>">
                <i class="dropdown-icon fe fe-log-out"></i>
                <%= I18n.t("terms_app.sign_out") %>
              </a>
            <% end %>

          </div>
        </div>

      </div>

      <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
        <span class="header-toggler-icon"></span>
      </a>
    </div>
  </div>
</div>
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg order-lg-first">

        <ul class="nav nav-tabs border-0 flex-column flex-lg-row">

          <% if PolicyManager::Config.is_admin?(controller.current_user) %>

            <li class="nav-item">
              <a class="nav-link" href="<%= categories_path %>">
                <i class="fas fa-balance-scale"></i>
                <%= I18n.t("terms_app.menu.policies") %>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="<%= portability_requests_path %>">
                <i class="fas fa-suitcase"></i>
                <%= I18n.t("terms_app.menu.portability_requests") %>
              </a>
            </li>

          <% end %>

          <% if controller.current_user.class.to_s == PolicyManager::Config.user_resource.to_s %>

            <li class="separator"></li>

            <li class="nav-item">
              <a class="nav-link" href="<%= pending_user_terms_path %>">
                <i class="fas fa-user-secret"></i>
                <%= I18n.t("terms_app.menu.user_pending_policies") %>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="<%= user_portability_requests_path %>">
                <i class="fas fa-suitcase"></i>
                <%= I18n.t("terms_app.menu.user_portability_requests") %>
              </a>
            </li>

          <% end %>

        </ul>
      </div>
    </div>
  </div>
</div>